# Generated by Django 4.1.7 on 2023-03-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=250)),
                ('userImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
